### ISSUE TITLE
Create a favorites model

### ISSUE THREAD

**Issue by PJonestown** [AnthonyBobsin/techether#1]
We'd DRY up the subjects, resources, and users controllers and move them more towards containing only CRUD operations.

**Comment by AnthonyBobsin** [comment]
That sounds excellent. I have been meaning to implement a separate favourites model. Do you have any suggestions on columns? Right now I have it so it appends onto a string the favourite separated by a comma. This isn't the greatest implementation. We could have a subject id, resource_id and user_id, and just create new rows every time somebody favourites a subject or resource.

**Comment by PJonestown** [comment]
The part that complicates things is that you can favorite both resources and subjects. I can think of two solutions:

The first being the type of model you suggested. Only that would be a favorite_resources model, and then we'd make one called favorite_subjects that would work the same way.

The other solution is a polymorphic association. We'd have one favorites model with a name:string user:references favoritable_type:string favoritable_id:integer. The favoritable_type would be either 'Resource' or 'Subject'. 

The first solution is simple to implement but has some code repetition and an extra table. The latter is a pain to implement(imho) but is DRY.

**Comment by PJonestown** [comment]
Also, perhaps this should be a separate issue, but I think this could be a good time to start working on test coverage. I was thinking of keeping it ultra simple. Integration tests for creating and removing favorites for both subjects and resources. Once we get some passing tests, we can start breaking and changing things up. 

I don't have any experience with minitest, but I don't imagine integration tests being too much of a problem. I could start working on the tests tomorrow if you'd like, and it'll give you some time to decide which road to take with the favorites model.

**Comment by AnthonyBobsin** [comment]
I think I'm going to implement something similar to my solution and your polymorphic association solution. It would have subject: references, resource: references, user: references, and favorite_type then check the reference depending on the favorite_type. Also thank you for reminding me on tests. I keep on pushing them back, and I agree right now is the perfect time to start. That would be great if you could start off the tests whenever you can as I haven't written Rails tests in quite a while.

**Comment by AnthonyBobsin** [comment]
Favourites model is now finished. It really cleaned up a lot of the code. The exact columns I used are subject:references, resource:references, user:references, and is_subject:boolean. It worked out pretty well, thanks for all the help!
